version: "3.8"

services:
  sweden_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sweden:
    build: .
    restart: always
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic
        --no-input && gunicorn -b 0.0.0.0:80 api.wsgi --reload"
    volumes:
      - .:/app
      - ./static:/static
    ports:
      - "80:80"
    depends_on:
      - sweden_db

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - sweden_db
      - sweden
    ports:
      - "88:88"
      - "443:443"

volumes:
  postgres_data: