# Generated by Django 4.0.3 on 2022-03-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_question_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='updated_date',
        ),
    ]
